name: test

on:
  push:
  pull_request:
  schedule: [cron: "40 1 * * *"]

jobs:
  test:
    name: Rust ${{matrix.rust}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [nightly, beta, stable, 1.13.0]
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
      - run: cargo build --manifest-path legacy-serde/legacy-serde-0.6/Cargo.toml
      - run: cargo build --manifest-path legacy-serde/legacy-serde-0.7/Cargo.toml
      - run: cargo build --manifest-path legacy-serde/legacy-serde-0.8/Cargo.toml
      - run: cargo build --manifest-path legacy-serde/legacy-serde-0.9/Cargo.toml
      - run: cargo build --manifest-path serde06/Cargo.toml
      - run: cargo build --manifest-path serde07/Cargo.toml
      - run: cargo build --manifest-path serde08/Cargo.toml
      - run: cargo build --manifest-path serde09/Cargo.toml
      - run: cargo build --manifest-path serde1/Cargo.toml
